site_name: Alex Dragan
custom_dir: docs/sources
extra_css:
  - sources/main/main.css
theme:
  font:
    text: 'TerminusTTF-Bold'
    code: 'TerminusTTF-Bold'
  name: 'material'
  logo: 'sources/icon/icon.png'
  fixed_nav: true
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: 'deep orange'
      toggle:
        icon: material/weather-night
        name: "Toggle dark mode"
    - scheme: slate
      primary: 'deep orange'
      toggle:
        icon: material/weather-sunny
        name: "Toggle light mode"
hooks:
  - mkdocs_hooks.py
  
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://darkdragon9870.github.io/mi_web/">Mi Pagina web</a> by <span property="cc:attributionName">Alex Dragan</span> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>
